const users = [{"id":1,"car":"Honda","color":"Purple"},
{"id":2,"car":"Pontiac","color":"Mauv"},
{"id":3,"car":"BMW","color":"Maroon"},
{"id":4,"car":"Volkswagen","color":"Purple"},
{"id":5,"car":"Audi","color":"Yellow"},
{"id":6,"car":"Toyota","color":"Mauv"},
{"id":7,"car":"Jaguar","color":"Puce"},
{"id":8,"car":"Chevrolet","color":"Orange"},
{"id":9,"car":"Oldsmobile","color":"Orange"},
{"id":10,"car":"Ferrari","color":"Orange"},
{"id":11,"car":"Oldsmobile","color":"Khaki"},
{"id":12,"car":"Infiniti","color":"Aquamarine"},
{"id":13,"car":"GMC","color":"Red"},
{"id":14,"car":"Nissan","color":"Puce"},
{"id":15,"car":"Kia","color":"Purple"},
{"id":16,"car":"Pontiac","color":"Yellow"},
{"id":17,"car":"Oldsmobile","color":"Yellow"},
{"id":18,"car":"GMC","color":"Red"},
{"id":19,"car":"Chevrolet","color":"Red"},
{"id":20,"car":"BMW","color":"Crimson"},
{"id":21,"car":"Jeep","color":"Violet"},
{"id":22,"car":"Nissan","color":"Yellow"},
{"id":23,"car":"Hyundai","color":"Pink"},
{"id":24,"car":"Toyota","color":"Yellow"},
{"id":25,"car":"Mercedes-Benz","color":"Khaki"},
{"id":26,"car":"GMC","color":"Puce"},
{"id":27,"car":"Honda","color":"Maroon"},
{"id":28,"car":"Audi","color":"Teal"},
{"id":29,"car":"GMC","color":"Khaki"},
{"id":30,"car":"GMC","color":"Pink"},
{"id":31,"car":"Honda","color":"Aquamarine"},
{"id":32,"car":"Ford","color":"Teal"},
{"id":33,"car":"Oldsmobile","color":"Violet"},
{"id":34,"car":"Buick","color":"Goldenrod"},
{"id":35,"car":"Kia","color":"Puce"},
{"id":36,"car":"Chevrolet","color":"Teal"},
{"id":37,"car":"Daewoo","color":"Puce"},
{"id":38,"car":"Rolls-Royce","color":"Aquamarine"},
{"id":39,"car":"Suzuki","color":"Purple"},
{"id":40,"car":"Dodge","color":"Purple"},
{"id":41,"car":"Mercedes-Benz","color":"Purple"},
{"id":42,"car":"GMC","color":"Fuscia"},
{"id":43,"car":"Nissan","color":"Green"},
{"id":44,"car":"Chevrolet","color":"Maroon"},
{"id":45,"car":"Porsche","color":"Indigo"},
{"id":46,"car":"Lincoln","color":"Green"},
{"id":47,"car":"Nissan","color":"Crimson"},
{"id":48,"car":"Audi","color":"Khaki"},
{"id":49,"car":"BMW","color":"Blue"},
{"id":50,"car":"Chevrolet","color":"Fuscia"},
{"id":51,"car":"GMC","color":"Green"},
{"id":52,"car":"Honda","color":"Orange"},
{"id":53,"car":"Pontiac","color":"Red"},
{"id":54,"car":"Scion","color":"Blue"},
{"id":55,"car":"Mercedes-Benz","color":"Aquamarine"},
{"id":56,"car":"Dodge","color":"Blue"},
{"id":57,"car":"Hyundai","color":"Yellow"},
{"id":58,"car":"Lamborghini","color":"Aquamarine"},
{"id":59,"car":"Buick","color":"Puce"},
{"id":60,"car":"Audi","color":"Fuscia"},
{"id":61,"car":"Saab","color":"Indigo"},
{"id":62,"car":"Lexus","color":"Yellow"},
{"id":63,"car":"Volkswagen","color":"Crimson"},
{"id":64,"car":"Infiniti","color":"Fuscia"},
{"id":65,"car":"Land Rover","color":"Goldenrod"},
{"id":66,"car":"Toyota","color":"Aquamarine"},
{"id":67,"car":"Mitsubishi","color":"Mauv"},
{"id":68,"car":"Mazda","color":"Maroon"},
{"id":69,"car":"Buick","color":"Blue"},
{"id":70,"car":"Ford","color":"Crimson"},
{"id":71,"car":"Suzuki","color":"Green"},
{"id":72,"car":"Kia","color":"Aquamarine"},
{"id":73,"car":"Ford","color":"Khaki"},
{"id":74,"car":"Chrysler","color":"Puce"},
{"id":75,"car":"Toyota","color":"Aquamarine"},
{"id":76,"car":"BMW","color":"Blue"},
{"id":77,"car":"Buick","color":"Mauv"},
{"id":78,"car":"Toyota","color":"Pink"},
{"id":79,"car":"Audi","color":"Crimson"},
{"id":80,"car":"GMC","color":"Pink"},
{"id":81,"car":"Chevrolet","color":"Turquoise"},
{"id":82,"car":"Mercedes-Benz","color":"Mauv"},
{"id":83,"car":"Pontiac","color":"Violet"},
{"id":84,"car":"Toyota","color":"Maroon"},
{"id":85,"car":"MINI","color":"Blue"},
{"id":86,"car":"Maserati","color":"Blue"},
{"id":87,"car":"Toyota","color":"Violet"},
{"id":88,"car":"Toyota","color":"Maroon"},
{"id":89,"car":"Lotus","color":"Green"},
{"id":90,"car":"Maserati","color":"Yellow"},
{"id":91,"car":"Mitsubishi","color":"Blue"},
{"id":92,"car":"Toyota","color":"Green"},
{"id":93,"car":"Nissan","color":"Turquoise"},
{"id":94,"car":"Ford","color":"Violet"},
{"id":95,"car":"GMC","color":"Crimson"},
{"id":96,"car":"Dodge","color":"Puce"},
{"id":97,"car":"Isuzu","color":"Indigo"},
{"id":98,"car":"Ford","color":"Green"},
{"id":99,"car":"Suzuki","color":"Teal"},
{"id":100,"car":"Mazda","color":"Aquamarine"}]

export const getUsers = function(page, limit){
    let array = [];
    for (let i = (page - 1) * limit; i < limit * page && users[i]; i++) {
        array.push(users[i]);
        
    }
    return array;
}

export const getLength = function(){
    return users.length;
}